# Generated by Django 4.0 on 2021-12-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makramapost',
            name='photo',
            field=models.ImageField(upload_to='makrama_images'),
        ),
    ]
