# Generated by Django 4.0 on 2021-12-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_makramapost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='makramapost',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
